version: '3.8'

services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    restart: unless-stopped

  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certResolver=letsencrypt
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - traefik

  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    environment:
      - TS_PORT=8090
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - ~/.torrserver/:/opt/ts
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrserver.entrypoints=websecure
      - traefik.http.routers.torrserver.tls=true
      - traefik.http.routers.torrserver.tls.certResolver=letsencrypt
      - traefik.http.services.torrserver.loadbalancer.server.port=8090
    networks:
      - traefik
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Novosibirsk
      - AUTO_UPDATE=true
      - RUN_OPTS= #optional
    volumes:
      - ~/.jackett/config:/config
      - ~/.jackett/downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.entrypoints=websecure
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certResolver=letsencrypt
      - traefik.http.services.jackett.loadbalancer.server.port=9117
    networks:
      - traefik
    restart: unless-stopped

  jacred:
    image: gentslava/jacred:latest
    container_name: jacred
    privileged: true
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.jacred/init.conf:/home/jacred/init.conf
      - ~/.jacred/Data:/home/jacred/Data
    labels:
      - traefik.enable=true
      - traefik.http.routers.jacred.entrypoints=websecure
      - traefik.http.routers.jacred.tls=true
      - traefik.http.routers.jacred.tls.certResolver=letsencrypt
      - traefik.http.services.jacred.loadbalancer.server.port=9117
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G

  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    privileged: true         # only for FFmpeg hardware transcoding
    environment:
      - TZ=Asia/Novosibirsk  # timezone in logs
    volumes:
      - "~/.go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)
    labels:
      - traefik.enable=true
      - traefik.http.routers.go2rtc.entrypoints=websecure
      - traefik.http.routers.go2rtc.tls=true
      - traefik.http.routers.go2rtc.tls.certResolver=letsencrypt
      - traefik.http.services.go2rtc.loadbalancer.server.port=1984
    networks:
      - traefik
    restart: unless-stopped  # autorestart on fail or config change from WebUI

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.frigate/config:/config
      - ~/.frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    labels:
      - traefik.enable=true
      - traefik.http.routers.frigate.entrypoints=websecure
      - traefik.http.routers.frigate.tls=true
      - traefik.http.routers.frigate.tls.certResolver=letsencrypt
      - traefik.http.services.frigate.loadbalancer.server.port=5000
    networks:
      - traefik
    restart: unless-stopped

  epicgames-freegames-node:
    image: ghcr.io/claabs/epicgames-freegames-node:latest
    container_name: epicgames-freegames
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.epicgames/:/usr/app/config:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.epicgames.entrypoints=websecure
      - traefik.http.routers.epicgames.tls=true
      - traefik.http.routers.epicgames.tls.certResolver=letsencrypt
      - traefik.http.services.epicgames.loadbalancer.server.port=3000
    networks:
      - traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant-test
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.hassio:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant-test.entrypoints=websecure
      - traefik.http.routers.homeassistant-test.tls=true
      - traefik.http.routers.homeassistant-test.tls.certResolver=letsencrypt
      - traefik.http.services.homeassistant-test.loadbalancer.server.port=8123
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_proxy
    external: true
