version: '3.3'
services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    restart: unless-stopped

  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certResolver=letsencrypt
    networks:
      - traefik

  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    environment:
      - TS_PORT=8090
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - ~/.torrserver/:/opt/ts
    ports:
      - 8090:8090
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Novosibirsk
      - AUTO_UPDATE=true
      - RUN_OPTS= #optional
    volumes:
      - ~/.jackett/config:/config
      - ~/.jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jacred:
    image: gentslava/jacred:latest
    container_name: jacred
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.jacred/init.conf:/home/jacred/init.conf
      - ~/.jacred/Data:/home/jacred/Data
    ports:
      - 9118:9117
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G

  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Asia/Novosibirsk  # timezone in logs
    volumes:
      - "~/.go2rtc:/config"   # folder for go2rtc.yaml file (edit from WebUI)

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.frigate/config:/config
      - ~/.frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp

  epicgames-freegames-node:
    image: ghcr.io/claabs/epicgames-freegames-node:latest
    container_name: epicgames-freegames
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.epicgames/:/usr/app/config:rw
    ports:
      - 6079:3000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant-test
    environment:
      - TZ=Asia/Novosibirsk
    volumes:
      - ~/.hassio:/config
    ports:
      - 8124:8123
    restart: unless-stopped

networks:
  traefik:
    name: traefik_proxy
    external: true
