version: '3.3'
services:
    torrserver:
        image: ghcr.io/yourok/torrserver
        container_name: torrserver
        environment:
            - TS_PORT=8090
            - TS_DONTKILL=1
            - TS_HTTPAUTH=0
            - TS_CONF_PATH=/opt/ts/config
            - TS_TORR_DIR=/opt/ts/torrents
        volumes:
            - ~/.torrserver/:/opt/ts
        ports:
            - 8090:8090
        restart: unless-stopped

    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - AUTO_UPDATE=true
            - RUN_OPTS= #optional
        volumes:
            - ~/.jackett/config:/config
            - ~/.jackett/downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped

    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/odroid-c2-homeassistant:stable
        volumes:
            - ~/.hassio/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
        ports:
            - 8123:8123
        restart: unless-stopped
        privileged: true
        network_mode: host
